// src/components/LifeCounter.vue
<script lang="ts" setup>
import { getProductiveYearsLeft, getYearsLeft, getYearsSpent } from "../utils/date";
import { currentUser } from "../store";
import { computed } from "vue";

const lifeYearsLeft = computed(() => {
    const user = currentUser.value;
    return getYearsLeft(new Date(user.dateOfBirth), user.expectedLifespan);
});

const productiveYearsLeft = computed(() => {
    const user = currentUser.value;
    return getProductiveYearsLeft(new Date(user.dateOfBirth), user.expectedLifespan);
});

const yearsSpent = computed(() => {
    const user = currentUser.value;
    return getYearsSpent(new Date(user.dateOfBirth));
});
</script>

<template>
    <div>
        <div>
            Прожито: <b>{{ yearsSpent }}</b>
        </div>
        <div>
            Продуктивной жизни осталось: <b>{{ productiveYearsLeft }}</b>
        </div>
        <div>
            Жить осталось: <b>{{ lifeYearsLeft }}</b>
        </div>
    </div>
</template>

<style scoped></style>

// src/components/life-counter/life-counter.tsx
import React, {useEffect, useState} from 'react';

import CSS from './life-counter.module.css'
import {User} from "../../domain";
import {getProductiveYearsLeft, getYearsLeft, getYearsSpent} from "../../utils/date";
import {getUser} from "../../domain/api/user";
import {useQuery} from "react-query";

function loadUser(userId: string) {
    const {isSuccess, data} = useQuery(
        `load_user_${userId}`,
        () => getUser(userId)
    )

    return data;
}

export const LifeCounter = () => {
    const user = loadUser('temp_id')

    if (!user) return <div className={CSS.container}>...</div>;

    return <div className={CSS.container}>
        Прожито: {getYearsSpent(user.dateOfBirth)}
        <br/>
        Продуктивной жизни осталось: {getProductiveYearsLeft(user.dateOfBirth, user.expectedLifespan)}
        <br/>
        Жить осталось: {getYearsLeft(user.dateOfBirth, user.expectedLifespan)}
    </div>
}
